on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: fvoon/github-actions-playground@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: |
          RANDOM_NUMBER="$RANDOM_NUMBER" &&
          echo random number "$((RANDOM_NUMBER * 6))"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}